names:
    # Names that you don't want players to use.  Use ALL LOWERCASE names.
    restricted:
        - me
        - here
        - north
        - south
        - east
        - west
        - northeast
        - northwest
        - southeast
        - southwest
        - look